//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapsInterfaceService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://maps.googleapis.com/maps/api/place/search/json?")]
        public string GooglePlacesApiBaseAddress {
            get {
                return ((string)(this["GooglePlacesApiBaseAddress"]));
            }
            set {
                this["GooglePlacesApiBaseAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}key={1}&location={2}&radius={3}&types={4}&sensor={5}")]
        public string GooglePlacesApiRequestFormat {
            get {
                return ((string)(this["GooglePlacesApiRequestFormat"]));
            }
            set {
                this["GooglePlacesApiRequestFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://maps.googleapis.com/maps/api/geocode/json?")]
        public string GoogleGeocodingApiBaseAddress {
            get {
                return ((string)(this["GoogleGeocodingApiBaseAddress"]));
            }
            set {
                this["GoogleGeocodingApiBaseAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}address={1}&sensor={2}")]
        public string GoogleGeocodingApiRequestFormat {
            get {
                return ((string)(this["GoogleGeocodingApiRequestFormat"]));
            }
            set {
                this["GoogleGeocodingApiRequestFormat"] = value;
            }
        }
    }
}
